# Assignment 2

For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

In [5]:
def proportion_of_education():
    
    import pandas as pd
    df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
    
    value_counts = df['EDUC1'].value_counts()
    
    one = value_counts.loc[1]/sum(value_counts)
    two = value_counts.loc[2]/sum(value_counts)
    three = value_counts.loc[3]/sum(value_counts)
    four = value_counts.loc[4]/sum(value_counts)

    my_results = {"less than high school":one,
                  "high school":two,
                  "more than high school but not college":three,
                  "college":four}
    
    return my_results
    

In [6]:
proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [ ]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


In [1]:
#import pandas as pd
#df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
#df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [12]:
#value_counts = df['EDUC1'].value_counts()
#value_counts

4    13656
3     6999
2     4906
1     2904
Name: EDUC1, dtype: int64

In [13]:
#value_counts.loc[1]

2904

In [14]:
#sum(value_counts)

28465

In [15]:
#1 = less than high school
#2 = high school
#3 = more than high school but not college
#4 = college

# Using loc, I am finding where the row name is 1
# if I had used iloc, then I would have found the index position, which would give incorrect results
#one = value_counts.loc[1]/sum(value_counts)
#two = value_counts.loc[2]/sum(value_counts)
#three = value_counts.loc[3]/sum(value_counts)
#four = value_counts.loc[4]/sum(value_counts)

#my_results = {"less than high school":one,
 #             "high school":two,
  #            "more than high school but not college":three,
   #           "college":four}

#my_results

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [31]:
def average_influenza_doses():
    import pandas as pd
    df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
    # Fed not fed
    fed = df[df['CBF_01'] == 1]
    not_fed = df[df['CBF_01'] == 2]

    #fed['P_NUMFLU'] = fed['P_NUMFLU'].fillna(0)
    #not_fed['P_NUMFLU'] = not_fed['P_NUMFLU'].fillna(0)

    fed = fed[fed.notna()]
    not_fed = not_fed[not_fed.notna()]

    store = (fed['P_NUMFLU'].mean(), not_fed['P_NUMFLU'].mean())
    
    return store

In [32]:
#average_influenza_doses()

(1.8799187420058687, 1.5963945918878317)

In [ ]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


In [8]:
#import pandas as pd
#df = pd.read_csv("assets/NISPUF17.csv", index_col=0)

In [9]:
#df['CBF_01'].unique()

array([ 1,  2, 99, 77])

In [10]:
#df['P_NUMFLU'].unique()

array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [ ]:
#P_NUMFLU

In [28]:
# Fed not fed
#fed = df[df['CBF_01'] == 1]
#not_fed = df[df['CBF_01'] == 2]

#fed['P_NUMFLU'] = fed['P_NUMFLU'].fillna(0)
#not_fed['P_NUMFLU'] = not_fed['P_NUMFLU'].fillna(0)

#fed = fed[fed.notna()]
#not_fed = not_fed[not_fed.notna()]

#store = (fed['P_NUMFLU'].mean(), not_fed['P_NUMFLU'].mean())

#print(store)

(1.8799187420058687, 1.5963945918878317)


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [62]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    import pandas as pd
    df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
    df=df[['HAD_CPOX','P_NUMVRC','SEX']]


    male = df[df['SEX']==1].dropna()
    female = df[df['SEX']==2].dropna()


    # MALE
    mle_vacc_got_df = male[(male['P_NUMVRC'] >= 1)&(male['HAD_CPOX'] == 1)]
    mle_vacc_got = (len(mle_vacc_got_df))

    mle_nv_dnt_df = male[(male['P_NUMVRC'] >= 1)&(male['HAD_CPOX'] == 2)]
    mle_nv_dnt = (len(mle_nv_dnt_df))

    male_val = mle_vacc_got/mle_nv_dnt


    # FEMALE
    fmle_vacc_got_df = female[(female['P_NUMVRC'] >= 1)&(female['HAD_CPOX'] == 1)]
    fmle_vacc_got = (len(fmle_vacc_got_df))

    fmle_nv_dnt_df = female[(female['P_NUMVRC'] >= 1)&(female['HAD_CPOX'] == 2)]
    fmle_nv_dnt = (len(fmle_nv_dnt_df))

    female_val = fmle_vacc_got/fmle_nv_dnt

    my_dict = {'female':female_val,          
               'male':male_val}

    return my_dict

In [ ]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


In [42]:
"""
print(df['HAD_CPOX'].unique())
print(df['P_NUMVRC'].unique())
print(df['SEX'].unique())
"""

[ 2  1 77 99]
[nan  1.  0.  2.  3.]
[1 2]


In [61]:
"""
import pandas as pd
df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
df=df[['HAD_CPOX','P_NUMVRC','SEX']]


male = df[df['SEX']==1].dropna()
female = df[df['SEX']==2].dropna()


# MALE
mle_vacc_got_df = male[(male['P_NUMVRC'] >= 1)&(male['HAD_CPOX'] == 1)]
mle_vacc_got = (len(mle_vacc_got_df))

mle_nv_dnt_df = male[(male['P_NUMVRC'] >= 1)&(male['HAD_CPOX'] == 2)]
mle_nv_dnt = (len(mle_nv_dnt_df))

male_val = mle_vacc_got/mle_nv_dnt


# FEMALE
fmle_vacc_got_df = female[(female['P_NUMVRC'] >= 1)&(female['HAD_CPOX'] == 1)]
fmle_vacc_got = (len(fmle_vacc_got_df))

fmle_nv_dnt_df = female[(female['P_NUMVRC'] >= 1)&(female['HAD_CPOX'] == 2)]
fmle_nv_dnt = (len(fmle_nv_dnt_df))

female_val = fmle_vacc_got/fmle_nv_dnt

my_dict = {'female':female_val,          
           'male':male_val}

my_dict
"""

{'female': 0.0077918259335489565, 'male': 0.009675583380762664}

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [71]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
    df = df[['HAD_CPOX','P_NUMVRC']].dropna()

    df = df[df['HAD_CPOX'] <= 2]

    corr, pval=stats.pearsonr(df["HAD_CPOX"],df["P_NUMVRC"])

    return corr

In [ ]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."


In [70]:
"""
# my working
import scipy.stats as stats
import numpy as np
import pandas as pd


df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
df = df[['HAD_CPOX','P_NUMVRC']].dropna()

df = df[df['HAD_CPOX'] <= 2]

corr, pval=stats.pearsonr(df["HAD_CPOX"],df["P_NUMVRC"])

print(corr, pval)

the correlation is low, and the P value is very low
which means we must accept the null hypothesis that there is no relationship between being vaccinated and getting chicken pox

"""

0.07044873460147986 2.7780263182916748e-18
